name: docker-scip

on:
  push:
    branches:
      - scip
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'Dockerfile.autoindex'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install asdf.
        uses: asdf-vm/actions/setup@v2.2.0
      - name: Cache asdf and asdf-managed tools.
        uses: actions/cache@v3.3.1
        id: asdf-cache
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-${{ runner.os}}-${{ hashFiles('**/.tool-versions') }}
      - name: Install asdf tools (if not cached).
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v2.2.0
      - name: Get npm cache directory
        id: npm-cache
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: cd ./packages/pyright-scip/ && npm install && npm run build
      - uses: docker/setup-buildx-action@v2
      - name: Build Dockerfile
        id: docker_build_autoindex
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.autoindex
          push: false
          tags: |
            sourcegraph/scip-python:test
