name: release-scip

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: '**/package-lock.json'
          node-version: 16
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npm ci && npm run build
        working-directory: ./packages/pyright-scip/

      - if: ${{ env.NODE_AUTH_TOKEN }}
        run: npm publish --access public
        working-directory: ./packages/pyright-scip/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  docker:
    needs: publish
    strategy:
      fail-fast: false
      matrix:
        version_debian: [bookworm]
        version_python: ['3.10']
        version_node: ['16']

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

      # Permissions used for artifact attestation.
      attestations: write
      id-token: write

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY || 'docker.io' }}
          username: ${{ secrets.DOCKER_USERNAME || github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}

      # Use QEMU and Buildx so we can build for multiple platforms.
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY || 'docker.io' }}/${{ github.repository }}
          flavor: |
            latest=true
          # NOTE: The autoindex tag seems to be legacy and overlaps fully with latest, dropping it might be breaking change.
          tags: |
            type=sha,
            type=schedule
            type=raw,value=autoindex
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and release image
        id: push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha,scope=docker-${{ matrix.version_debian}}-${{ matrix.version_python}}-${{ matrix.version_node }}
          cache-to: type=gha,mode=max,scope=docker-${{ matrix.version_debian}}-${{ matrix.version_python}}-${{ matrix.version_node }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |-
            VERSION_DEBIAN=${{ matrix.version_debian }}
            VERSION_PYTHON=${{ matrix.version_python }}
            VERSION_NODE=${{ matrix.version_node }}
            VERSION_SCIP_PYTHON=${{ github.ref_name }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ vars.REGISTRY || 'docker.io' }}/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
