name: release-scip

on:
  push:
    tags:
      - v*

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: cd ./packages/pyright-scip/ && npm install && npm run build
      - run: cd ./packages/pyright-scip/ && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build_autoindex
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.autoindex
          push: true
          tags: |
            sourcegraph/scip-python:autoindex
            sourcegraph/scip-python:latest
            sourcegraph/scip-python:${{ github.ref_name }}
