name: 'formatting'

env:
  NODE_VERSION: '16'

on:
  push:
    branches:
      - main
      - scip
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name: check

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install

      - run: npm install
        working-directory: packages/pyright-scip

      - name: Check prettier formatting
        run: npm run check:prettier
        working-directory: packages/pyright-scip
